### ISSUE TITLE
day1

### ISSUE THREAD

**Issue by bryantchan** [willhamlam/design_job#1]
做得不错哦, 有几个建议提一下:
- 虽然是静态页面, 但是还是要加上注释这样我好看点. 
- 页面命名要规范, index就是index, 很少有Homepage的
- slider要做成效果. 静态页面包括jquery的实现. 你可以参考用这个Royalslider去实现: 

[Document](http://dimsemenov.com/plugins/royal-slider/documentation/)
[Demo](http://dimsemenov.com/plugins/royal-slider/gallery-vertical-fade/)
[Download](https://dl.dropbox.com/u/37315730/resource/royalslider.zip)

![Screen Shot 2013-02-26 at 10 33 47 AM](https://f.cloud.github.com/assets/1303409/194754/fb6d5f4e-7fbc-11e2-8814-f52bc2081696.png)

keep in touch

**Comment by willhamlam** [comment]
…我觉得做的很烂耶…..=_=….不过今天做的这部分sidebar和footer比较会用模块化…快了很多…然后开始就可以在content部分改动即可…那个slider就是我想问你的…昨天找了一些找不到就用图片顶着…感谢提醒

## 

Best regards,

William Lam

在 2013年2月26日星期二，上午10:38，Bryant 写道：
